### ISSUE TITLE
Change logger level dinamically

### ISSUE THREAD

**Issue by vincenzopalazzo** [sapristi/easy_logging#2]
Maybe this problem was covered from this issue https://github.com/sapristi/easy_logging/issues/1 and maybe it only my limit with OCaml.

I'm using this in the library in one of my projects with Ocaml and I'm searching the possibility to change the log level dinamically without change the code.

In other words, I have my application statically logger and I want to introduce the feature to run it with a flag --debug and has the level changed inside the logger.

It is possible to have this feature with the library, if yes can suggest me an example to reproduce it inside my application?

Thanks.

**Comment by sapristi** [comment]
Hello, 
yes it is totally possible to change the log level dynamically.
You can see a real-life example here:  https://github.com/sapristi/alife/blob/dev/src/bin/yaacs_server.ml

There is also a generic example here: https://github.com/sapristi/alife/blob/dev/src/gui/server/logs_server.ml (where logs level are set by web requests).

Basically, all you have to do is retrieve the logger you want to set with `Logging.get_logger` and then use the `set_level` method:

```ocaml
let logger = logging.get_logger "my.logger" in
logger#set_level "debug"
```

**Comment by vincenzopalazzo** [comment]
Oh, thanks so much :) and sorry for the stupid question
