### ISSUE TITLE
Version 0.8 missed from opam

### ISSUE THREAD

**Issue by vincenzopalazzo** [sapristi/easy_logging#3]
Hello, I'm not able to found the last version of this package on opam https://opam.ocaml.org/packages/easy_logging/easy_logging.0.7.1/ there is some mistake here?

**Comment by aryx** [comment]
Also, would it be possible to update the code to use ppx_deriving >= 5.0?
I'm using a few packages which rely on the recent ppx_deriving, which means I can't use easy_logging at the same time.

Thanks.

**Comment by sapristi** [comment]
Hello both, sorry @vincenzopalazzo for the delayed answer.
There is no other reason for v0.8 not being on opam other than me being lazy. I will try to do this as soon as possible.
As for using a more recent version of ppx_deriving, it should be totally possible, I have not been following the recent developments but I'm only using basic features.

@aryx It's been some time I haven't worked on this project, and am out of internet (except for 4g from my phone) at home right now, so it might take a few weeks for me to fix this, If you feel like doing a PR for this it would be great. Thus in the meantime you could also use this version on your projects (either by pinning a local repo or a github branch, see e.g here: https://stackoverflow.com/questions/25277599/how-to-install-from-a-specific-git-branch-with-opam )

**Comment by vincenzopalazzo** [comment]
hello @sapristi,

for me there is any problem, I just asking. Thanks so much

**Comment by sapristi** [comment]
Ok I checked again what was in v0.8, and there isn't any new feature; on the contrary, I tried to simplify the internals and removed the `MakeLogging` functor. So you're not missing anything ;)
I will publish a version with updated `ppx_deriving` when I have more stable internet.

**Comment by aryx** [comment]
Great! Thx sapristi. Keep up the good work!

**Comment by aryx** [comment]
Ok I'll maybe try to make a PR for updating ppx_deriving then. I have conflicts between 2 libraries I'm using because of it.

**Comment by aryx** [comment]
ok, just tried to compile with ppx_deriving 5.2.1 and it works perfectly fine. The restrictions in easy_logging_yojson.opam are not necessary.

**Comment by sapristi** [comment]
The release 0.8.2 is pending in opam, which is compatible with ppx_deriving 5

**Comment by vincenzopalazzo** [comment]
I will close this issue @sapristi thanks!
