### ISSUE TITLE
GPL license -> LGPL?

### ISSUE THREAD

**Issue by aryx** [sapristi/easy_logging#4]
Using the GPL license for a library is quite invasive. Did you do it on purpose @sapristi ? Most OCaml libraries
are distributed under the LGPL (and many of them have an addition on about linking).
See for example https://github.com/returntocorp/semgrep/blob/develop/LICENSE

**Comment by aryx** [comment]
see what's github says about the LGPL:
"GNU Lesser General Public License v2.1
Primarily used for software libraries, the GNU LGPL requires that derived works be licensed under the same license, but works that only link to it do not fall under this restriction"

**Comment by sapristi** [comment]
Hello, yes this was on purpose.  My main view on the subject is that I wouldn't feel very comfortable with the library being used in closed source programs.

Do you have a precise use-case where the GPL license is problematic ?

**Comment by aryx** [comment]
Well I'm working for a company where some parts of our work is open source (the OCaml program I'm developping, semgrep.dev),  and other parts are closed source, and our lawyers hate the GPL ... It's like kryptonite to them, so if you use a GPL library, even in your open source code, it's like a huge red signals for them. I might have to switch to another logging library then ...
Thanks for your work anyway!

**Comment by sapristi** [comment]
Hmm ok I will see what I can do about that, for the next ( soon I hope ! ) release of easy-logging.

**Comment by sapristi** [comment]
The release 0.8.2 is pending in opam, with Mozilla Public License 2.0 (basically allows using the library however you want, only modifications are subject to the license).

**Comment by aryx** [comment]
Fantastic! Merci!

**Comment by dra27** [comment]
In b4d89023dcf68fb104b7fe8c701b48c10d27 you switched the `LICENSE` file to MPL but all the source files still state GPL.

**Comment by sapristi** [comment]
@dra27 thanks for the report. I have updated the files in `master`, the opam publication seem to be failing, but this should be fixed in a few days ;)

**Comment by dra27** [comment]
> the opam publication seem to be failing

Looking briefly at the PR, you have `(lang dune 1.8.0)` in your `dune-project` file which should be `(lang dune 1.8)` which will clear the lint errors - there's obviously a lowerbound missing on one of your dependencies, but I expect that one of the opam-repo maintainers will recognise that one and push a fix!

**Comment by sapristi** [comment]
Thanks for the feedback on the opam PR, that's most definitely useful ;)

**Comment by sapristi** [comment]
@dra27 0.8.2 was merged !
